version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"

  app:
    image: wafa003/achat:1.0
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      - mysql
